### ISSUE TITLE
Rewrite in a proper langauge

### ISSUE THREAD

**Issue by BIGPHATTOBY** [Emil8250/movie-waffle#1]
To further enable public contribution I propose changing to a more OSS adopted language... May I suggest Golang?

**Comment by Emil8250** [comment]
You may indeed suggest Golang. 
While we regard your suggestion, please consider this use my course: https://www.udemy.com/course/csharp-tutorial-for-beginners/

**Comment by Emil8250** [comment]
We decided not to use Golang. Sorry!
